// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

// Import user types
import { BountyStatus, Verification } from "../common.sol";

struct BountyData {
  BountyStatus status;
  Verification verification;
  uint32 rewardCents;
  int32 x;
  int32 z;
  uint64 updatedAt;
  uint32 scoutCount;
}

library Bounty {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "frontier", name: "Bounty", typeId: RESOURCE_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x746266726f6e74696572000000000000426f756e747900000000000000000000);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x001a070001010404040804000000000000000000000000000000000000000000);

  // Hex-encoded key schema of (uint256)
  Schema constant _keySchema = Schema.wrap(0x002001001f000000000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (uint8, uint8, uint32, int32, int32, uint64, uint32)
  Schema constant _valueSchema = Schema.wrap(0x001a070000000323230703000000000000000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](1);
    keyNames[0] = "jobId";
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](7);
    fieldNames[0] = "status";
    fieldNames[1] = "verification";
    fieldNames[2] = "rewardCents";
    fieldNames[3] = "x";
    fieldNames[4] = "z";
    fieldNames[5] = "updatedAt";
    fieldNames[6] = "scoutCount";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get status.
   */
  function getStatus(uint256 jobId) internal view returns (BountyStatus status) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(jobId));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return BountyStatus(uint8(bytes1(_blob)));
  }

  /**
   * @notice Get status.
   */
  function _getStatus(uint256 jobId) internal view returns (BountyStatus status) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(jobId));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return BountyStatus(uint8(bytes1(_blob)));
  }

  /**
   * @notice Set status.
   */
  function setStatus(uint256 jobId, BountyStatus status) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(jobId));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked(uint8(status)), _fieldLayout);
  }

  /**
   * @notice Set status.
   */
  function _setStatus(uint256 jobId, BountyStatus status) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(jobId));

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked(uint8(status)), _fieldLayout);
  }

  /**
   * @notice Get verification.
   */
  function getVerification(uint256 jobId) internal view returns (Verification verification) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(jobId));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return Verification(uint8(bytes1(_blob)));
  }

  /**
   * @notice Get verification.
   */
  function _getVerification(uint256 jobId) internal view returns (Verification verification) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(jobId));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return Verification(uint8(bytes1(_blob)));
  }

  /**
   * @notice Set verification.
   */
  function setVerification(uint256 jobId, Verification verification) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(jobId));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked(uint8(verification)), _fieldLayout);
  }

  /**
   * @notice Set verification.
   */
  function _setVerification(uint256 jobId, Verification verification) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(jobId));

    StoreCore.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked(uint8(verification)), _fieldLayout);
  }

  /**
   * @notice Get rewardCents.
   */
  function getRewardCents(uint256 jobId) internal view returns (uint32 rewardCents) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(jobId));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Get rewardCents.
   */
  function _getRewardCents(uint256 jobId) internal view returns (uint32 rewardCents) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(jobId));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Set rewardCents.
   */
  function setRewardCents(uint256 jobId, uint32 rewardCents) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(jobId));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((rewardCents)), _fieldLayout);
  }

  /**
   * @notice Set rewardCents.
   */
  function _setRewardCents(uint256 jobId, uint32 rewardCents) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(jobId));

    StoreCore.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((rewardCents)), _fieldLayout);
  }

  /**
   * @notice Get x.
   */
  function getX(uint256 jobId) internal view returns (int32 x) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(jobId));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (int32(uint32(bytes4(_blob))));
  }

  /**
   * @notice Get x.
   */
  function _getX(uint256 jobId) internal view returns (int32 x) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(jobId));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (int32(uint32(bytes4(_blob))));
  }

  /**
   * @notice Set x.
   */
  function setX(uint256 jobId, int32 x) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(jobId));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((x)), _fieldLayout);
  }

  /**
   * @notice Set x.
   */
  function _setX(uint256 jobId, int32 x) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(jobId));

    StoreCore.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((x)), _fieldLayout);
  }

  /**
   * @notice Get z.
   */
  function getZ(uint256 jobId) internal view returns (int32 z) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(jobId));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 4, _fieldLayout);
    return (int32(uint32(bytes4(_blob))));
  }

  /**
   * @notice Get z.
   */
  function _getZ(uint256 jobId) internal view returns (int32 z) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(jobId));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 4, _fieldLayout);
    return (int32(uint32(bytes4(_blob))));
  }

  /**
   * @notice Set z.
   */
  function setZ(uint256 jobId, int32 z) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(jobId));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 4, abi.encodePacked((z)), _fieldLayout);
  }

  /**
   * @notice Set z.
   */
  function _setZ(uint256 jobId, int32 z) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(jobId));

    StoreCore.setStaticField(_tableId, _keyTuple, 4, abi.encodePacked((z)), _fieldLayout);
  }

  /**
   * @notice Get updatedAt.
   */
  function getUpdatedAt(uint256 jobId) internal view returns (uint64 updatedAt) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(jobId));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 5, _fieldLayout);
    return (uint64(bytes8(_blob)));
  }

  /**
   * @notice Get updatedAt.
   */
  function _getUpdatedAt(uint256 jobId) internal view returns (uint64 updatedAt) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(jobId));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 5, _fieldLayout);
    return (uint64(bytes8(_blob)));
  }

  /**
   * @notice Set updatedAt.
   */
  function setUpdatedAt(uint256 jobId, uint64 updatedAt) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(jobId));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 5, abi.encodePacked((updatedAt)), _fieldLayout);
  }

  /**
   * @notice Set updatedAt.
   */
  function _setUpdatedAt(uint256 jobId, uint64 updatedAt) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(jobId));

    StoreCore.setStaticField(_tableId, _keyTuple, 5, abi.encodePacked((updatedAt)), _fieldLayout);
  }

  /**
   * @notice Get scoutCount.
   */
  function getScoutCount(uint256 jobId) internal view returns (uint32 scoutCount) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(jobId));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 6, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Get scoutCount.
   */
  function _getScoutCount(uint256 jobId) internal view returns (uint32 scoutCount) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(jobId));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 6, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Set scoutCount.
   */
  function setScoutCount(uint256 jobId, uint32 scoutCount) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(jobId));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 6, abi.encodePacked((scoutCount)), _fieldLayout);
  }

  /**
   * @notice Set scoutCount.
   */
  function _setScoutCount(uint256 jobId, uint32 scoutCount) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(jobId));

    StoreCore.setStaticField(_tableId, _keyTuple, 6, abi.encodePacked((scoutCount)), _fieldLayout);
  }

  /**
   * @notice Get the full data.
   */
  function get(uint256 jobId) internal view returns (BountyData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(jobId));

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreSwitch.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Get the full data.
   */
  function _get(uint256 jobId) internal view returns (BountyData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(jobId));

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreCore.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(
    uint256 jobId,
    BountyStatus status,
    Verification verification,
    uint32 rewardCents,
    int32 x,
    int32 z,
    uint64 updatedAt,
    uint32 scoutCount
  ) internal {
    bytes memory _staticData = encodeStatic(status, verification, rewardCents, x, z, updatedAt, scoutCount);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(jobId));

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(
    uint256 jobId,
    BountyStatus status,
    Verification verification,
    uint32 rewardCents,
    int32 x,
    int32 z,
    uint64 updatedAt,
    uint32 scoutCount
  ) internal {
    bytes memory _staticData = encodeStatic(status, verification, rewardCents, x, z, updatedAt, scoutCount);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(jobId));

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function set(uint256 jobId, BountyData memory _table) internal {
    bytes memory _staticData = encodeStatic(
      _table.status,
      _table.verification,
      _table.rewardCents,
      _table.x,
      _table.z,
      _table.updatedAt,
      _table.scoutCount
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(jobId));

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function _set(uint256 jobId, BountyData memory _table) internal {
    bytes memory _staticData = encodeStatic(
      _table.status,
      _table.verification,
      _table.rewardCents,
      _table.x,
      _table.z,
      _table.updatedAt,
      _table.scoutCount
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(jobId));

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(
    bytes memory _blob
  )
    internal
    pure
    returns (
      BountyStatus status,
      Verification verification,
      uint32 rewardCents,
      int32 x,
      int32 z,
      uint64 updatedAt,
      uint32 scoutCount
    )
  {
    status = BountyStatus(uint8(Bytes.getBytes1(_blob, 0)));

    verification = Verification(uint8(Bytes.getBytes1(_blob, 1)));

    rewardCents = (uint32(Bytes.getBytes4(_blob, 2)));

    x = (int32(uint32(Bytes.getBytes4(_blob, 6))));

    z = (int32(uint32(Bytes.getBytes4(_blob, 10))));

    updatedAt = (uint64(Bytes.getBytes8(_blob, 14)));

    scoutCount = (uint32(Bytes.getBytes4(_blob, 22)));
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   *
   *
   */
  function decode(
    bytes memory _staticData,
    EncodedLengths,
    bytes memory
  ) internal pure returns (BountyData memory _table) {
    (
      _table.status,
      _table.verification,
      _table.rewardCents,
      _table.x,
      _table.z,
      _table.updatedAt,
      _table.scoutCount
    ) = decodeStatic(_staticData);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord(uint256 jobId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(jobId));

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord(uint256 jobId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(jobId));

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(
    BountyStatus status,
    Verification verification,
    uint32 rewardCents,
    int32 x,
    int32 z,
    uint64 updatedAt,
    uint32 scoutCount
  ) internal pure returns (bytes memory) {
    return abi.encodePacked(status, verification, rewardCents, x, z, updatedAt, scoutCount);
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(
    BountyStatus status,
    Verification verification,
    uint32 rewardCents,
    int32 x,
    int32 z,
    uint64 updatedAt,
    uint32 scoutCount
  ) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData = encodeStatic(status, verification, rewardCents, x, z, updatedAt, scoutCount);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple(uint256 jobId) internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(jobId));

    return _keyTuple;
  }
}
