// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

struct ScoutData {
  uint64 at;
  bool harvested;
}

library Scout {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "frontier", name: "Scout", typeId: RESOURCE_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x746266726f6e7469657200000000000053636f75740000000000000000000000);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x0009020008010000000000000000000000000000000000000000000000000000);

  // Hex-encoded key schema of (uint256, bytes32)
  Schema constant _keySchema = Schema.wrap(0x004002001f5f0000000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (uint64, bool)
  Schema constant _valueSchema = Schema.wrap(0x0009020007600000000000000000000000000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](2);
    keyNames[0] = "jobId";
    keyNames[1] = "player";
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](2);
    fieldNames[0] = "at";
    fieldNames[1] = "harvested";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get at.
   */
  function getAt(uint256 jobId, bytes32 player) internal view returns (uint64 at) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(jobId));
    _keyTuple[1] = player;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint64(bytes8(_blob)));
  }

  /**
   * @notice Get at.
   */
  function _getAt(uint256 jobId, bytes32 player) internal view returns (uint64 at) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(jobId));
    _keyTuple[1] = player;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint64(bytes8(_blob)));
  }

  /**
   * @notice Set at.
   */
  function setAt(uint256 jobId, bytes32 player, uint64 at) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(jobId));
    _keyTuple[1] = player;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((at)), _fieldLayout);
  }

  /**
   * @notice Set at.
   */
  function _setAt(uint256 jobId, bytes32 player, uint64 at) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(jobId));
    _keyTuple[1] = player;

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((at)), _fieldLayout);
  }

  /**
   * @notice Get harvested.
   */
  function getHarvested(uint256 jobId, bytes32 player) internal view returns (bool harvested) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(jobId));
    _keyTuple[1] = player;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (_toBool(uint8(bytes1(_blob))));
  }

  /**
   * @notice Get harvested.
   */
  function _getHarvested(uint256 jobId, bytes32 player) internal view returns (bool harvested) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(jobId));
    _keyTuple[1] = player;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (_toBool(uint8(bytes1(_blob))));
  }

  /**
   * @notice Set harvested.
   */
  function setHarvested(uint256 jobId, bytes32 player, bool harvested) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(jobId));
    _keyTuple[1] = player;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((harvested)), _fieldLayout);
  }

  /**
   * @notice Set harvested.
   */
  function _setHarvested(uint256 jobId, bytes32 player, bool harvested) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(jobId));
    _keyTuple[1] = player;

    StoreCore.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((harvested)), _fieldLayout);
  }

  /**
   * @notice Get the full data.
   */
  function get(uint256 jobId, bytes32 player) internal view returns (ScoutData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(jobId));
    _keyTuple[1] = player;

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreSwitch.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Get the full data.
   */
  function _get(uint256 jobId, bytes32 player) internal view returns (ScoutData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(jobId));
    _keyTuple[1] = player;

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreCore.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(uint256 jobId, bytes32 player, uint64 at, bool harvested) internal {
    bytes memory _staticData = encodeStatic(at, harvested);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(jobId));
    _keyTuple[1] = player;

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(uint256 jobId, bytes32 player, uint64 at, bool harvested) internal {
    bytes memory _staticData = encodeStatic(at, harvested);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(jobId));
    _keyTuple[1] = player;

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function set(uint256 jobId, bytes32 player, ScoutData memory _table) internal {
    bytes memory _staticData = encodeStatic(_table.at, _table.harvested);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(jobId));
    _keyTuple[1] = player;

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function _set(uint256 jobId, bytes32 player, ScoutData memory _table) internal {
    bytes memory _staticData = encodeStatic(_table.at, _table.harvested);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(jobId));
    _keyTuple[1] = player;

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(bytes memory _blob) internal pure returns (uint64 at, bool harvested) {
    at = (uint64(Bytes.getBytes8(_blob, 0)));

    harvested = (_toBool(uint8(Bytes.getBytes1(_blob, 8))));
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   *
   *
   */
  function decode(
    bytes memory _staticData,
    EncodedLengths,
    bytes memory
  ) internal pure returns (ScoutData memory _table) {
    (_table.at, _table.harvested) = decodeStatic(_staticData);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord(uint256 jobId, bytes32 player) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(jobId));
    _keyTuple[1] = player;

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord(uint256 jobId, bytes32 player) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(jobId));
    _keyTuple[1] = player;

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(uint64 at, bool harvested) internal pure returns (bytes memory) {
    return abi.encodePacked(at, harvested);
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(uint64 at, bool harvested) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData = encodeStatic(at, harvested);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple(uint256 jobId, bytes32 player) internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(jobId));
    _keyTuple[1] = player;

    return _keyTuple;
  }
}

/**
 * @notice Cast a value to a bool.
 * @dev Boolean values are encoded as uint8 (1 = true, 0 = false), but Solidity doesn't allow casting between uint8 and bool.
 * @param value The uint8 value to convert.
 * @return result The boolean value.
 */
function _toBool(uint8 value) pure returns (bool result) {
  assembly {
    result := value
  }
}
