// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { TotemInput } from "../../TotemInput.sol";

/**
 * @title IOracleSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IOracleSystem {
  error LengthMismatch();
  error BadStatus();
  error BadVerification();

  function frontier__syncMeta(
    uint32 chainId,
    bool realMoney,
    string calldata environment,
    string calldata source,
    address marketContract,
    uint32 beaconCount,
    uint32 totemCount
  ) external;

  function frontier__syncBounties(
    uint256[] calldata jobIds,
    uint8[] calldata statuses,
    uint8[] calldata verifications,
    uint32[] calldata rewardCents
  ) external;

  function frontier__syncTotems(TotemInput[] calldata totems) external;

  function frontier__clearTotems(uint8 from, uint8 to) external;
}
