// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IScoutSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IScoutSystem {
  error NoSuchBounty();
  error BountySettled();
  error TooFar();
  error AlreadyScouted();
  error NoSpark();
  error NotCompleted();
  error NotScouted();
  error AlreadyHarvested();

  function frontier__scout(uint256 jobId) external;

  function frontier__harvest(uint256 jobId) external;
}
