// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

enum BountyStatus {
  None,
  Open,
  Accepted,
  Submitted,
  Completed,
  Cancelled,
  Disputed,
  Refunded,
  Expired
}

enum Verification {
  Unknown,
  ManualReview,
  AutoGradedTests,
  IndependentGrader,
  CiChecks
}
