// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { WorldMeta, WorldMetaData } from "./tables/WorldMeta.sol";
import { Player, PlayerData } from "./tables/Player.sol";
import { Position, PositionData } from "./tables/Position.sol";
import { Bounty, BountyData } from "./tables/Bounty.sol";
import { Totem, TotemData } from "./tables/Totem.sol";
import { Scout, ScoutData } from "./tables/Scout.sol";
